name: Commit Message Validation

on:
  pull_request:
    branches:
      - main

env:
  GOPRIVATE: github.com/RiemaLabs

jobs:
  commit-message-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: CI/CD commit and code format checking
      run: |
        make ci
