name: Commit Message Validation

on:
  pull_request:
    branches:
      - main

jobs:
  commit-message-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Query commits
      run: |
        #!/bin/bash
        commits_url="${{ github.event.pull_request._links.commits.href }}"
        commits=$(curl -sSL $commits_url)

    - name: Validate Commit Messages
      run: |
        #!/bin/bash
        INVALID_COMMIT_FORMAT_REGEX="^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\(.+\))?:\ .+"
        commits_url="${{ github.event.pull_request._links.commits.href }}"
        commits=$(curl -sSL $commits_url)
        echo "$commits"
        commit_shas=$(echo "$commits" | jq -r '.[] | .sha')
        for sha in $commit_shas; do
          echo "$sha"
          message=$(git log --format="%H %s" -n 1 $sha)
          echo "$message"
          # Check if it's a merge commit
          if [[ $message =~ .*Merge\ .+\ into\ .+$ ]]; then
            continue
          fi

          if [[ ! $message =~ $INVALID_COMMIT_FORMAT_REGEX ]]; then
            echo "Invalid commit message format: $message"
            exit 1
          fi
        done
