name: Build and Release

on:
  release:
    types:
      - published

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build for Linux
        run: |
          make clean
          make GOOS=linux GOARCH=amd64
          zip modular-indexer-light-linux-amd64.zip config.example.json modular-indexer-light run.sh

      - name: Build for macOS amd64
        run: |
          make clean
          make GOOS=darwin GOARCH=amd64
          zip modular-indexer-light-darwin-amd64.zip config.example.json modular-indexer-light run.sh

      - name: Build for macOS arm64
        run: |
          make clean
          make GOOS=darwin GOARCH=arm64
          zip modular-indexer-light-darwin-arm64.zip config.example.json modular-indexer-light run.sh

      - name: Build for Windows
        run: |
          make clean
          make GOOS=windows GOARCH=amd64
          zip modular-indexer-light-windows-amd64.zip config.example.json modular-indexer-light.exe run.bat

      - name: Upload Release Assets linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./modular-indexer-light-linux-amd64.zip
          asset_name: modular-indexer-light-linux-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Assets darwin amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./modular-indexer-light-darwin-amd64.zip
          asset_name: modular-indexer-light-darwin-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Assets darwin arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./modular-indexer-light-darwin-arm64.zip
          asset_name: modular-indexer-light-darwin-arm64.zip
          asset_content_type: application/zip

      - name: Upload Release Assets windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./modular-indexer-light-windows-amd64.zip
          asset_name: modular-indexer-light-windows-amd64.zip
          asset_content_type: application/zip
